### ISSUE TITLE
does not build on ubuntu 12.04

### ISSUE THREAD

**Issue by kennyplaces** [zeromq/jzmq#114]
Its been working flawlessly on ubuntu 11 and 10, but once we move the env to 12.04, the compilation failed on "make": 

ubuntu@ip-10-72-110-107:~/zeromq-jzmq-fe47a77$ make
Making all in src
make[1]: Entering directory `/home/ubuntu/zeromq-jzmq-fe47a77/src'
make[1]: *** No rule to make target`classdist_noinst.stamp', needed by `org/zeromq/ZMQ.class'.  Stop.
make[1]: Leaving directory`/home/ubuntu/zeromq-jzmq-fe47a77/src'
make: **\* [all-recursive] Error 1

I checked the makfile under src, and the classdist_noinst.stamp target is actually missing, so it must be something wrong while doing "configure", but there wasnt any error for that.

Could someone help please?

thanks,
kenny

**Comment by snehalparmar** [comment]
The solution of @TigerZhang works.

**Comment by klion26** [comment]
@ebroder ur solution works for me, thank you.
