### ISSUE TITLE
JZMQ 2.2.0 does not compile and build with native ZMQ 2.2.0

### ISSUE THREAD

**Issue by mauri-melato** [zeromq/jzmq#233]
[root@casteddu jzmq-2.2.0]# make
Making all in src
make[1]: Entering directory `/home/nice/src/new/jzmq-2.2.0/src'
make  all-am
make[2]: Entering directory`/home/nice/src/new/jzmq-2.2.0/src'
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.   -D_REENTRANT -D_THREAD_SAFE  -I /home/nice/src/new/zeromq2-x-2.2.0/include -I/usr/lib/jvm/java-1.6.0-openjdk.x86_64/include -I/usr/lib/jvm/java-1.6.0-openjdk.x86_64/include/linux -Wall -g -O2 -MT libjzmq_la-Socket.lo -MD -MP -MF .deps/libjzmq_la-Socket.Tpo -c -o libjzmq_la-Socket.lo `test -f 'Socket.cpp' || echo './'`Socket.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -D_REENTRANT -D_THREAD_SAFE -I /home/nice/src/new/zeromq2-x-2.2.0/include -I/usr/lib/jvm/java-1.6.0-openjdk.x86_64/include -I/usr/lib/jvm/java-1.6.0-openjdk.x86_64/include/linux -Wall -g -O2 -MT libjzmq_la-Socket.lo -MD -MP -MF .deps/libjzmq_la-Socket.Tpo -c Socket.cpp  -fPIC -DPIC -o .libs/libjzmq_la-Socket.o
Socket.cpp: In function 'jint Java_org_zeromq_ZMQ_00024Socket_sendByteBuffer(JNIEnv_, _jobject_, _jobject_, jint)':
Socket.cpp:576: error: cannot convert 'jbyte_' to 'zmq_msg_t_' for argument '2' to 'int zmq_send(void_, zmq_msg_t_, int)'
Socket.cpp: In function 'jint Java_org_zeromq_ZMQ_00024Socket_recvByteBuffer(JNIEnv_, _jobject_, _jobject_, jint)':
Socket.cpp:708: error: cannot convert 'jbyte_' to 'zmq_msg_t_' for argument '2' to 'int zmq_recv(void_, zmq_msg_t_, int)'
Socket.cpp: At global scope:
Socket.cpp:507: warning: 'jboolean s_zerocopy_init(JNIEnv_, zmq_msg_t_, _jobject_, jint)' defined but not used
make[2]: *_\* [libjzmq_la-Socket.lo] Error 1
make[2]: Leaving directory `/home/nice/src/new/jzmq-2.2.0/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory`/home/nice/src/new/jzmq-2.2.0/src'
make: **\* [all-recursive] Error 1
